[package]
name = "vortex"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pdf = {git = "https://github.com/omkar-mohanty/pdf.git" , branch = "png_flate"} 
html = "0.5.2"
clap = { version =  "4.2.4" , features = ["derive"] }
log = "0.4.0"
env_logger = "0.9.0"
image = "0.24.6"
